# Generated by Django 4.2.10 on 2024-02-23 07:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/img/account/profile_default', null=True, storage=account.models.CustomFileSystemStorage(), upload_to=account.models.user_directory_path),
        ),
    ]
