# Generated by Django 4.2.10 on 2024-03-01 07:05

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=account.models.CustomFileSystemStorage(), upload_to=account.models.user_directory_path),
        ),
    ]
