# Generated by Django 4.2.10 on 2024-03-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Additional_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
