# Generated by Django 4.2.10 on 2024-02-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('item_explain', models.TextField()),
                ('item_category', models.CharField(max_length=100)),
                ('item_condition', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
