# Generated by Django 4.2.10 on 2024-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_item_image_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
