# Generated by Django 4.2.10 on 2024-03-01 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_item_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='LikeUsers',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
